server:
  port: 8089
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
jwt:
  token:
    pubKeyPath: D:\idea-projects\rsa\rsa.pub
    priKeyPath: D:\idea-projects\rsa\rsa.pri
    secret: ncjsdklfhurilgsjfhlrkdgurlsh*#
    cookieName: gmall_token
    expireTime: 30